apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
  namespace: gitlab-o3s
spec:
  secretName: gitlab-tls
  issuerRef:
    name: gitlab-issuer
    kind: Issuer
  commonName: gitlab.rancher.pointertech.digital
  dnsNames:
    - gitlab.rancher.pointertech.digital
    - kas.rancher.pointertech.digital
  duration: 2160h
  renewBefore: 360h
