# ==============================
# Grafana Configuration 
# ==============================
persistence:
  enabled: true
  size: 10Gi
  storageClass: "longhorn"

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 500Mi

ingress:
  enabled: true
  ingressClassName: gitlab-nginx
  annotations:
    cert-manager.io/issuer: gitlab-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/priority: "10"
  hosts:
    - grafana.rancher.pointertech.digital
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.rancher.pointertech.digital

adminPassword: "GitLabGrafana123!"