apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-gitlab
spec:
  acme:
    email: gustavo.costa@extreme.digital
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-gitlab-key
    solvers:
      - http01:
          ingress:
            class: gitlab-nginx