apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard-tls
  namespace: gitlab-o3s
spec:
  secretName: gitlab-wildcard-tls
  issuerRef:
    name: gitlab-issuer
    kind: Issuer
  dnsNames:
  - gitlab.rancher.pointertech.digital
  - registry.rancher.pointertech.digital
  - minio.rancher.pointertech.digital
  - prometheus.rancher.pointertech.digital
  - grafana.rancher.pointertech.digital
  - kas.rancher.pointertech.digital
  - "*.rancher.pointertech.digital"
